server:
  port: 8761  # Port where Eureka Server will run

spring:
  application:
    name: eureka-server  # Name for the Eureka Server application

eureka:
  server:
    enable-self-preservation: false  # Optional: Disable self-preservation for testing
  client:
    register-with-eureka: false  # Server doesn't register itself with Eureka
    fetch-registry: false  # Don't fetch other service registrations
